### ISSUE TITLE
API token in config yields "Invalid API key in config file"

### ISSUE THREAD

**Issue by syre** [marten-cz/loco-cli#10]
Switching from the previous version this config no longer works:
```
api:
  token: <deleted>
pull: {}
push:
  delete-absent: 'false'
  ignore-existing: 'true'
  ignore-new: 'false'
  index: text
  locale: en
translations:
- file: publish/static_dev/translations/source.po
  format: po
  locale: en
- file: publish/static_dev/translations/es.po
  format: po
  locale: es
- file: publish/static_dev/translations/da.po
  format: po
  locale: da
```
> Unknown project identificator "default". Check that your config is in project parent.

adding `default:` at the top yields:

> Invalid API key in config file

using the newly created `-t` seems to work.
